### ISSUE TITLE
choose a database

### ISSUE THREAD

**Issue by GlenDC** [threefoldfoundation/iexplorer#1]
We need a database which allows us to index everything, such that we can query anything we would ever wan to query in order to search and explore any data on the blockchain, directly and very fast from this database instance.

`iexplorer` will be used to populate data into a database instance, clients consuming the data however talk/query directly to/from that database instance.

**Comment by GlenDC** [comment]
<https://github.com/elastic/elasticsearch> seems to be the most promising open source search engine technology we can check. Data is stored in it as well, using some simple REST calls, making it easy enough to populate. <https://github.com/olivere/elastic> seems like a nice Go client that we can use from the `iexplorer` code.

As a fallback I would suggest either an SQL database or MongoDB, but for now elastic-search is the one to go for I think.

**Comment by NuclearCookie** [comment]
As discussed in private, this seems te best solution to get started with 👍
